apiVersion: v1
kind: Pod
metadata:
  name: triage
spec:
  containers:
  - name: triage
      image: meepsh/toolbox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
