source <(antibody init)
antibody bundle <<BUNDLE
ohmyzsh/ohmyzsh
ohmyzsh/ohmyzsh path:plugins/fzf
ohmyzsh/ohmyzsh path:themes/jonathan.zsh-theme
zsh-users/zsh-autosuggestions
zsh-users/zsh-syntax-highlighting
zsh-users/zsh-completions
chisui/zsh-nix-shell
BUNDLE

setopt autocd extendedglob notify
bindkey -e
zstyle :compinstall filename "$HOME/.zshrc"

# zsh-autosuggestion color highlighting and key bindings
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#ff5f00"
bindkey '^E' autosuggest-accept
bindkey '^ ' forward-word

alias vim="nvim"
alias ne="nix-env"
alias ns="nix-shell"
alias nc="nix-channel"

